export const COUNT_LOAD = 'COUNT_LOAD';

export const COUNT_RESET = 'COUNT_RESET';
export const COUNT_RESET_RESOLVED = 'COUNT_RESET_RESOLVED';

export const COUNT_INCREASE = 'COUNT_INCREASE';
export const COUNT_INCREASE_RESOLVED = 'COUNT_INCREASE_RESOLVED';

export const COUNT_DECREASE = 'COUNT_DECREASE';
export const COUNT_DECREASE_RESOLVED = 'COUNT_DECREASE_RESOLVED';
